### ISSUE TITLE
Store an entire app state between page reloads

### ISSUE THREAD

**Issue by kravets-levko** [openspending/os-packager#37]
* [x] On accidental (or not) reload of a page, we'd expect the user to still see her data from the current "session". Therefore, we need to serialise the data state in local storage

**Comment by pwalsh** [comment]
@kravets-levko we will have to tackle this now, as in order to do https://github.com/openspending/os-packager/issues/50 we'll be sending the user on an auth journey and eventually redirecting her back to here with a [JSON Web Token](https://jwt.io). Therefore, the application state needs to be accessible on the redirect back.

**Comment by pwalsh** [comment]
DONE.
